#!/usr/bin/env spang2
# @endpoint ortho
# @input (9606)
# @option -a

SELECT ?taxid ?label
WHERE {
  VALUES (?tax) { {{INPUT}} }
  BIND(URI(CONCAT("http://identifiers.org/taxonomy/", ?tax)) AS ?taxid)
  ?taxid rdfs:label ?label .
}
ORDER BY ?taxid
